apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-build
spec:
  params:
    - name: image-name
      type: string
      description: The name of the image to build.
  workspaces:
    - name: source
  steps:
    - name: build
      image: docker
      script: |
        cd $(workspaces.source.path)
        docker build -t $(params.image-name) .
