apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-image-task
spec:
  params:
    - name: image-name
      description: The name of the image to push.
  steps:
    - name: push-to-nexus
      image: gcr.io/google.com/cloudsdktool/cloud-sdk
      script: |
        docker login <nexus-url> -u _json_key -p "$(cat /tekton/home/.docker/config.json)"
        docker push <nexus-url>/<nexus-repository>/$(params.image-name)
  volumes:
    - name: docker-config
      secret:
        secretName: <nexus-username-password-secret> # The secret containing your Nexus username and password.
