apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: code-scan-build-and-push
spec:
  params:
    - name: repo-url
      type: string
      description: The URL of the Git repository.
    - name: revision
      type: string
      description: The revision of the Git repository.
    - name: registry
      type: string
      description: The registry to which we push the image.
    - name: image-name
      type: string
      description: The name of the image to be pushed.
  tasks:
    - name: scan-code
      taskRef:
        name: scan-code-task
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: build-image
      taskRef:
        name: build-image-task
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
      runAfter:
        - scan-code
    - name: push-image
      taskRef:
        name: push-image-task
      params:
        - name: image-name
          value: $(params.image-name)
        - name: registry
          value: $(params.registry)
      runAfter:
        - build-image
