apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  params:
    - name: repository
      type: string
    - name: revision
      type: string
    - name: sonarHost
      type: string
    - name: sonarLogin
      type: string
    - name: image-name
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: code-scan
      taskRef:
        name: sonarqube-scan
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: sonarHost
          value: $(params.sonarHost)
        - name: sonarLogin
          value: $(params.sonarLogin)
    - name: build-image
      taskRef:
        name: docker-build
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image-name
          value: $(params.image-name)
      runAfter:
        - code-scan
    - name: image-scan
      taskRef:
        name: trivy-scan
      params:
        - name: image-name
          value: $(params.image-name)
      runAfter:
        - build-image
    - name: push-image
      taskRef:
        name: push-image-task
      params:
        - name: image-name
          value: $(params.image-name)
      runAfter:
        - image-scan
