apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: my-pipeline-run
spec:
  pipelineRef:
    name: my-pipeline
  params:
    - name: repository
      value: https://github.com/EAS-Max/testApp.git
    - name: revision
      value: main
    - name: sonarHost
      value: <sonarqube host>
    - name: sonarLogin
      value: <sonarqube login token>
    - name: image-name
      value: testApp:latest
